

import Head from 'next/head';
import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
     children: React.ReactNode;
   }>) {

  return (
    <html lang="en">
    <Head>
      {/*<meta name="viewport" content="width=device-width, initial-scale=1.0"/>*/}
      <meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"/>
      <meta name="apple-mobile-web-app-capable" content="yes"/>
    </Head>

    <body className={`${GeistSans.className} ${GeistMono.className}`}>
      {children}
    </body>
    </html>
  );
}
