import {JotaiProvider} from '@/app/lib/components/JotaiProvider';
import { NextThemesProvider } from '@/app/lib/theme-provider';
import NextTopLoader from 'nextjs-toploader';
import AuthSessionProvider from '@/components/providers/session-provider';
import { ProcessingMask } from '@/app/lib/components/ProcessingMask';
import { ToastContainer } from 'react-toastify';

import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import React from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
      <link rel="stylesheet" href="/fonts/local.css"/>
    </head>
    <body
      className="antialiased font-sans"
      suppressHydrationWarning
    >
    <NextTopLoader
      color="#2299DD"
      initialPosition={0.08}
      crawlSpeed={200}
      height={3}
      crawl={true}
      showSpinner={true}
      easing="ease"
      speed={200}
      shadow="0 0 10px #2299DD,0 0 5px #2299DD"
    />
    <NextThemesProvider attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
    >
      <AuthSessionProvider>
        <JotaiProvider>
          {children}
          <ProcessingMask />
        </JotaiProvider>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="auto"
        />
      </AuthSessionProvider>
    </NextThemesProvider>
    </body>
    </html>
  )
}
