import {JotaiProvider} from '@/app/lib/components/JotaiProvider';
import { NextThemesProvider } from '@/app/lib/theme-provider';
import AuthSessionProvider from '@/components/providers/session-provider';

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <link rel="stylesheet" href="/fonts/fonts.css" />
    </head>
    <body
      className="antialiased font-sans"
      suppressHydrationWarning
    >
    <NextThemesProvider attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
    >
      <AuthSessionProvider>
        <JotaiProvider>{children}</JotaiProvider>
      </AuthSessionProvider>
    </NextThemesProvider>
    </body>
    </html>
  )
}
