import React from "react";
import {InitColorSchemeScript} from '@mui/material';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';

import {JotaiProvider} from '@/app/lib/components/JotaiProvider';
import { NextThemesProvider } from '@/app/lib/theme-provider';
import NextTopLoader from 'nextjs-toploader';
import AuthSessionProvider from '@/components/providers/session-provider';
import { ProcessingMask } from '@/app/lib/components/ProcessingMask';
import { ToastContainer } from 'react-toastify';

import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  titleTemplate: '%s',  // %s 被页面 title 替换
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
      <meta name="emotion-insertion-point" content=""/>
      <link rel="stylesheet" href="/fonts/local.css"/>
    </head>
    <body className="antialiased font-sans" suppressHydrationWarning>
    <InitColorSchemeScript attribute="class"/>
    <AppRouterCacheProvider options={{enableCssLayer: true}}>
      <NextTopLoader initialPosition={0.08} height={3}
                     crawlSpeed={200} speed={200} easing="ease"
                     crawl={true}
                     showSpinner={true}
                     color="#2299DD" shadow="0 0 10px #2299DD,0 0 5px #2299DD"/>
    <NextThemesProvider attribute="class"
                        disableTransitionOnChange>
      <AuthSessionProvider>
        <JotaiProvider>
          {children}
          <ProcessingMask />
        </JotaiProvider>
        <ToastContainer newestOnTop={true} position="top-right" rtl={false}
                        autoClose={3000} hideProgressBar={false}
                        draggable pauseOnHover pauseOnFocusLoss closeOnClick
                        theme="auto"/>
      </AuthSessionProvider>
    </NextThemesProvider>

    </AppRouterCacheProvider>
    </body>
    </html>
  )
}
